### ISSUE TITLE
"Authentication failed" with otherwise working davmail.properties file

### ISSUE THREAD

**Issue by waldner** [kran0/davmail-docker#5]
I'm using `connectical/davmail:6.0.1` which is working fine but I wanted to find a more recent image, so trying with:

```
  davmail:
    image: kran0/davmail-docker:6.2.0
    hostname: davmail
    container_name: davmail
    restart: always
    volumes:
      - ./davmail.properties:/davmail/davmail.properties
    ports:
      - "1025:1025"
      - "1389:1389"
      - "1110:1110"
      - "1143:1143"
      - "1080:1080"
```

The `davmail.properties` is the one that was working with the previous image.
But as soon as I try to fetch mail I get a java exception:

```
davmail    | 2024-01-04 17:50:42,934 ERROR [ImapConnection-57066] davmail  - Authentication failed: invalid user or password
davmail    | davmail.exception.DavMailAuthenticationException: Authentication failed: invalid user or password
davmail    | 	at davmail.exchange.ews.EwsExchangeSession.checkEndPointUrl(EwsExchangeSession.java:228)
davmail    | 	at davmail.exchange.ews.EwsExchangeSession.buildSessionInfo(EwsExchangeSession.java:237)
davmail    | 	at davmail.exchange.ews.EwsExchangeSession.<init>(EwsExchangeSession.java:176)
davmail    | 	at davmail.exchange.ews.EwsExchangeSession.<init>(EwsExchangeSession.java:205)
davmail    | 	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:192)
davmail    | 	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:93)
davmail    | 	at davmail.imap.ImapConnection.run(ImapConnection.java:155)
```

So not sure where to look. Any help welcome. I'm attaching the properties file (slightly redacted).
