### ISSUE TITLE
listener is not working with https

### ISSUE THREAD

**Issue by Spartacus68** [kran0/davmail-docker#6]
I need to configure the https listener vor carddav and seems to be not working:

compose.yaml:
```
version: '3'
services:
  davmail:
    image: kran0/davmail-docker:latest
    hostname: davmail
    volumes:
       - /share/VirtualMachine/Container/DavMail/config:/davmail-config # To save persistent conf data
    environment:
      - DAVMAIL_SERVER=true
      - DAVMAIL_ALLOWREMOTE=true
      - DAVMAIL_DISABLEUPDATECHECK=true
      - DAVMAIL_LOGFILEPATH=/dev/stdout
      - DAVMAIL_CALDAVPORT=1080
      - DAVMAIL_IMAPPORT=1143
      - DAVMAIL_LDAPPORT=1389
      - DAVMAIL_POPPORT=1110
      - DAVMAIL_SMTPPORT=1025
      - JAVA_OPTS=-Xmx512M -Dsun.net.inetaddr.ttl=30
#      - DISABLE_DAVMAIL_PROPERTIES_PERSISTENCE=true
    ports:
      - 1080:1080
      - 1143:1143
      - 1389:1389
      - 1110:1110
      - 1025:1025
    restart: on-failure

    networks:
      vlan:
       ipv4_address: 172.16.10.99
volumes:
  davmail-config:
networks:
  vlan:
    driver: macvlan
    driver_opts:
      parent: eth3.10 # schema is {INTERFACE}.{VLAN ID}
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24
          gateway: 172.16.10.1
```

Files in    - /share/VirtualMachine/Container/DavMail/config:/davmail-config 
```
davmail.properties
davmail.p12
```
davmail.properties:
```
# DavMail listeners SSL configuration
davmail.ssl.keystoreType=PKCS12
davmail.ssl.keystoreFile=davmail.p12
davmail.ssl.keystorePass=password
davmail.ssl.keyPass=password
```

Log, if I try to request from the client:
```
2024-02-21 16:23:02,780 ERROR [CaldavConnection-53953] davmail  - Invalid header, HTTPS connection to an HTTP listener ?
davmail.exception.DavMailException: Invalid header, HTTPS connection to an HTTP listener ?
        at davmail.caldav.CaldavConnection.parseHeaders(CaldavConnection.java:108)
        at davmail.caldav.CaldavConnection.run(CaldavConnection.java:163)
```
The key was generated by with:
```
keytool -genkey -keyalg rsa -keysize 2048 -storepass password -keystore davmail.p12 -storetype
pkcs12 -validity 3650 -dname cn=davmailhostname.company.com,ou=davmail,o=sf,o=net
```
direclley in davmail

**Comment by kran0** [comment]
Thank you for your feedback.
The problem is in this setting: `davmail.ssl.keystoreFile=davmail.p12`, this path must be either relative to the Working directory (which is /) or better be absolute. E.g.: `davmail.ssl.keystoreFile=/davmail-config/davmail.p12`. Or set `working_dir:` option in compose `service: davmail`.

Please follow this recommendations too:
1. While using env-based config, do not set manual properties in `/share/VirtualMachine/Container/DavMail/config/*.preperties` file. You should set DAVMAIL_SSL_KEYSTOREFILE in environment (and other properties too).
2. Because of previous, you should not mount evternal volume to /davmail-config. To place `davmail.p12`, please use another location, like: `/davmail-secrets` or anything else.
```
  services:
    volumes:
       - davmail-config:/davmail-config # To save persistent conf data
       - /share/VirtualMachine/Container/DavMail/config:/davmail-secret # To save persistent conf data
    environment:
      - DAVMAIL_SSL_KEYSTOREFILE=/davmail-secret/davmail.p12
  volumes:
    davmail-config:
```

Please try to fix the config and return your feedback. Thank you.
